---
repository:
  default_branch: main

  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true

  has_issues: true
  has_wiki: false
  has_projects: false

  squash_merge_commit_title: "PR_TITLE"
  squash_merge_commit_message: "BLANK"
